import type {
  TargetMember,
} from "@tsonic/tsts";
import {
  nodeBufferAllocMemberId,
  nodeBufferAllocSignatureId,
  nodeBufferAllocUnsafeMemberId,
  nodeBufferAllocUnsafeSignatureId,
  nodeBufferAllocUnsafeSlowMemberId,
  nodeBufferAllocUnsafeSlowSignatureId,
  nodeBufferAtobSignatureId,
  nodeBufferBtoaSignatureId,
  nodeBufferByteLengthMemberId,
  nodeBufferByteLengthSignatureId,
  nodeBufferCompareMemberId,
  nodeBufferCompareSignatureId,
  nodeBufferConcatMemberId,
  nodeBufferConcatSignatureId,
  nodeBufferEqualsMemberId,
  nodeBufferEqualsSignatureId,
  nodeBufferFromStringMemberId,
  nodeBufferFromStringSignatureId,
  nodeBufferIsAsciiSignatureId,
  nodeBufferIsEncodingMemberId,
  nodeBufferIsEncodingSignatureId,
  nodeBufferIsUtf8SignatureId,
  nodeBufferLengthMemberId,
  nodeBufferOfMemberId,
  nodeBufferOfSignatureId,
  nodeBufferSliceMemberId,
  nodeBufferSliceSignatureId,
  nodeBufferSubarrayMemberId,
  nodeBufferSubarraySignatureId,
  nodeBufferToStringMemberId,
  nodeBufferToStringSignatureId,
} from "./identities.js";
import {
  getNodeBufferEqualsTargetMember,
  getNodeBufferLengthTargetMember,
  getNodeBufferSliceTargetMember,
  getNodeBufferSubarrayTargetMember,
  getNodeBufferToStringTargetMember,
} from "./instance-members.js";
import {
  getNodeBufferAllocTargetMember,
  getNodeBufferAllocUnsafeSlowTargetMember,
  getNodeBufferAllocUnsafeTargetMember,
  getNodeBufferAtobTargetMember,
  getNodeBufferBtoaTargetMember,
  getNodeBufferByteLengthTargetMember,
  getNodeBufferCompareTargetMember,
  getNodeBufferConcatTargetMember,
  getNodeBufferFromStringTargetMember,
  getNodeBufferIsAsciiTargetMember,
  getNodeBufferIsEncodingTargetMember,
  getNodeBufferIsUtf8TargetMember,
  getNodeBufferOfTargetMember,
} from "./static-members.js";

export {
  getNodeBufferLengthTargetMember,
} from "./instance-members.js";

export function getNodeBufferTargetMember(memberId: string | undefined, signatureId: string | undefined): TargetMember | undefined {
  return nodeBufferTargetMembersByIdentity.get(signatureId ?? memberId ?? "");
}

const nodeBufferTargetMembersByIdentity = new Map<string, TargetMember>([
  [nodeBufferFromStringMemberId, getNodeBufferFromStringTargetMember()],
  [nodeBufferFromStringSignatureId, getNodeBufferFromStringTargetMember()],
  [nodeBufferAllocMemberId, getNodeBufferAllocTargetMember()],
  [nodeBufferAllocSignatureId, getNodeBufferAllocTargetMember()],
  [nodeBufferAllocUnsafeMemberId, getNodeBufferAllocUnsafeTargetMember()],
  [nodeBufferAllocUnsafeSignatureId, getNodeBufferAllocUnsafeTargetMember()],
  [nodeBufferAllocUnsafeSlowMemberId, getNodeBufferAllocUnsafeSlowTargetMember()],
  [nodeBufferAllocUnsafeSlowSignatureId, getNodeBufferAllocUnsafeSlowTargetMember()],
  [nodeBufferByteLengthMemberId, getNodeBufferByteLengthTargetMember()],
  [nodeBufferByteLengthSignatureId, getNodeBufferByteLengthTargetMember()],
  [nodeBufferCompareMemberId, getNodeBufferCompareTargetMember()],
  [nodeBufferCompareSignatureId, getNodeBufferCompareTargetMember()],
  [nodeBufferConcatMemberId, getNodeBufferConcatTargetMember()],
  [nodeBufferConcatSignatureId, getNodeBufferConcatTargetMember()],
  [nodeBufferEqualsMemberId, getNodeBufferEqualsTargetMember()],
  [nodeBufferEqualsSignatureId, getNodeBufferEqualsTargetMember()],
  [nodeBufferIsEncodingMemberId, getNodeBufferIsEncodingTargetMember()],
  [nodeBufferIsEncodingSignatureId, getNodeBufferIsEncodingTargetMember()],
  [nodeBufferLengthMemberId, getNodeBufferLengthTargetMember()],
  [nodeBufferOfMemberId, getNodeBufferOfTargetMember()],
  [nodeBufferOfSignatureId, getNodeBufferOfTargetMember()],
  [nodeBufferSliceMemberId, getNodeBufferSliceTargetMember()],
  [nodeBufferSliceSignatureId, getNodeBufferSliceTargetMember()],
  [nodeBufferSubarrayMemberId, getNodeBufferSubarrayTargetMember()],
  [nodeBufferSubarraySignatureId, getNodeBufferSubarrayTargetMember()],
  [nodeBufferToStringMemberId, getNodeBufferToStringTargetMember()],
  [nodeBufferToStringSignatureId, getNodeBufferToStringTargetMember()],
  [nodeBufferAtobSignatureId, getNodeBufferAtobTargetMember()],
  [nodeBufferBtoaSignatureId, getNodeBufferBtoaTargetMember()],
  [nodeBufferIsAsciiSignatureId, getNodeBufferIsAsciiTargetMember()],
  [nodeBufferIsUtf8SignatureId, getNodeBufferIsUtf8TargetMember()],
]);
