<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)/../../../../.temp/dotnet-provider-fixtures/recursive-delegates-msbuild-obj/</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
