import type { Node } from "@tsonic/tsts";
import type {
  SourceAstNode,
} from "./source-ast-types.js";

export const AsArrayLiteralExpression = cast;
export const AsArrowFunction = cast;
export const AsAsExpression = cast;
export const AsAwaitExpression = cast;
export const AsBigIntLiteral = cast;
export const AsBinaryExpression = cast;
export const AsBindingElement = cast;
export const AsBindingPattern = cast;
export const AsBlock = cast;
export const AsBreakStatement = cast;
export const AsCallExpression = cast;
export const AsCaseBlock = cast;
export const AsCaseOrDefaultClause = cast;
export const AsCatchClause = cast;
export const AsClassDeclaration = cast;
export const AsClassStaticBlockDeclaration = cast;
export const AsConditionalExpression = cast;
export const AsConstructorDeclaration = cast;
export const AsContinueStatement = cast;
export const AsDeleteExpression = cast;
export const AsDoStatement = cast;
export const AsElementAccessExpression = cast;
export const AsEnumDeclaration = cast;
export const AsEnumMember = cast;
export const AsExportAssignment = cast;
export const AsExpressionStatement = cast;
export const AsExpressionWithTypeArguments = cast;
export const AsForInOrOfStatement = cast;
export const AsForStatement = cast;
export const AsFunctionDeclaration = cast;
export const AsFunctionExpression = cast;
export const AsGetAccessorDeclaration = cast;
export const AsHeritageClause = cast;
export const AsIdentifier = cast;
export const AsIfStatement = cast;
export const AsIndexSignatureDeclaration = cast;
export const AsInterfaceDeclaration = cast;
export const AsLabeledStatement = cast;
export const AsMethodDeclaration = cast;
export const AsMethodSignatureDeclaration = cast;
export const AsNewExpression = cast;
export const AsNoSubstitutionTemplateLiteral = cast;
export const AsNonNullExpression = cast;
export const AsNumericLiteral = cast;
export const AsObjectLiteralExpression = cast;
export const AsParameterDeclaration = cast;
export const AsParenthesizedExpression = cast;
export const AsPostfixUnaryExpression = cast;
export const AsPrefixUnaryExpression = cast;
export const AsPrivateIdentifier = cast;
export const AsPropertyAccessExpression = cast;
export const AsPropertyAssignment = cast;
export const AsPropertyDeclaration = cast;
export const AsPropertySignatureDeclaration = cast;
export const AsRegularExpressionLiteral = cast;
export const AsReturnStatement = cast;
export const AsSatisfiesExpression = cast;
export const AsSetAccessorDeclaration = cast;
export const AsShorthandPropertyAssignment = cast;
export const AsSpreadAssignment = cast;
export const AsSpreadElement = cast;
export const AsStringLiteral = cast;
export const AsSwitchStatement = cast;
export const AsTemplateExpression = cast;
export const AsTemplateSpan = cast;
export const AsThrowStatement = cast;
export const AsTryStatement = cast;
export const AsTypeAssertion = cast;
export const AsTypeParameterDeclaration = cast;
export const AsTypeReferenceNode = cast;
export const AsVariableDeclaration = cast;
export const AsVariableDeclarationList = cast;
export const AsVariableStatement = cast;
export const AsVoidExpression = cast;
export const AsWhileStatement = cast;
export const AsYieldExpression = cast;

function cast(node: Node | undefined): SourceAstNode | undefined {
  return node as SourceAstNode | undefined;
}
