import type { Node } from "@tsonic/tsts";

export interface SourceAstNodeList<T = SourceAstNode> {
  readonly Nodes?: readonly (T | undefined)[];
}

export type SourceAstNode<T extends object = object> = Node & T & {
  readonly ArgumentExpression?: SourceAstNode;
  readonly AsteriskToken?: SourceAstNode;
  readonly Arguments?: SourceAstNodeList;
  readonly AwaitModifier?: SourceAstNode;
  readonly Block?: SourceAstNode;
  readonly Body?: SourceAstNode;
  readonly CaseBlock?: SourceAstNode;
  readonly CatchClause?: SourceAstNode;
  readonly Clauses?: SourceAstNodeList;
  readonly Condition?: SourceAstNode;
  readonly Constraint?: SourceAstNode;
  readonly DeclarationList?: SourceAstNode;
  readonly Declarations?: SourceAstNodeList;
  readonly DefaultType?: SourceAstNode;
  readonly DotDotDotToken?: SourceAstNode;
  readonly ElementType?: SourceAstNode;
  readonly Elements?: SourceAstNodeList;
  readonly ElseStatement?: SourceAstNode;
  readonly Expression?: SourceAstNode;
  readonly FinallyBlock?: SourceAstNode;
  readonly Flags?: number;
  readonly Head?: SourceAstNode;
  readonly HeritageClauses?: SourceAstNodeList;
  readonly Incrementor?: SourceAstNode;
  readonly Initializer?: SourceAstNode;
  readonly IsExportEquals?: boolean;
  readonly Label?: SourceAstNode;
  readonly Left?: SourceAstNode;
  readonly Literal?: SourceAstNode;
  readonly Members?: SourceAstNodeList;
  readonly OperatorToken?: SourceAstNode;
  readonly Parameters?: SourceAstNodeList;
  readonly Parent?: SourceAstNode;
  readonly Properties?: SourceAstNodeList;
  readonly PropertyName?: SourceAstNode;
  readonly QuestionDotToken?: SourceAstNode;
  readonly Right?: SourceAstNode;
  readonly Statement?: SourceAstNode;
  readonly Statements?: SourceAstNodeList;
  readonly TemplateSpans?: SourceAstNodeList;
  readonly Text?: string;
  readonly ThenStatement?: SourceAstNode;
  readonly Token?: SourceAstNode;
  readonly TryBlock?: SourceAstNode;
  readonly Type?: SourceAstNode;
  readonly TypeName?: SourceAstNode;
  readonly TypeParameters?: SourceAstNodeList;
  readonly Types?: SourceAstNodeList;
  readonly VariableDeclaration?: SourceAstNode;
  readonly WhenFalse?: SourceAstNode;
  readonly WhenTrue?: SourceAstNode;
  readonly ObjectAssignmentInitializer?: SourceAstNode;
  readonly Operand?: SourceAstNode;
  readonly name?: SourceAstNode;
};
